name: Run Transformation Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # List the files in the root directory for debugging
      - name: List files in the root directory
        run: |
          ls -R

      # List files in taf_dec/tests/table4 to verify transformation.py is there
      - name: List files in taf_dec/tests/table4
        run: |
          ls -R taf_dec/tests/table4

      # Cache Python dependencies (if needed)
      - name: Cache Python dependencies (if needed)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ github.sha }}  # Force cache reset

      # Debug the current directory
      - name: Check current working directory
        run: pwd

      # Run the Python transformation script using absolute path
      - name: Run transformation script
        run: |
          python ./taf_dec/tests/table4/transformation.py
