name: Run Transformation Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to list files for debugging
      - name: List files in taf_dec/tests/table4
        run: |
          ls -R taf_dec/tests/table4

      # Cache dependencies (no caching in this case)
      - name: Cache Python dependencies (if needed)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ github.sha }}  # Force cache reset

      - name: Run transformation script
        run: |
          cd taf_dec/tests/table4
          python3 transformation.py
