name: etlbigdataautomation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install Spark
    - name: Install Apache Spark
      run: |
        wget -qO- https://archive.apache.org/dist/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.2.tgz | tar xvz -C /opt/
        export SPARK_HOME=/opt/spark-3.3.0-bin-hadoop3.2
        export PATH=$SPARK_HOME/bin:$PATH

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Download Spark JARs
    - name: Download Spark JARs
      run: |
        mkdir -p $HOME/spark-jars
        curl -L -o $HOME/spark-jars/snowflake-jdbc-3.22.0.jar https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.22.0/snowflake-jdbc-3.22.0.jar
        curl -L -o $HOME/spark-jars/postgresql-42.2.5.jar https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.jar
        curl -L -o $HOME/spark-jars/azure-storage-8.6.6.jar https://repo1.maven.org/maven2/com/microsoft/azure/azure-storage/8.6.6/azure-storage-8.6.6.jar
        curl -L -o $HOME/spark-jars/hadoop-azure-3.3.1.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure/3.3.1/hadoop-azure-3.3.1.jar
        curl -L -o $HOME/spark-jars/mssql-jdbc-12.2.0.jre8.jar https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.2.0.jre8/mssql-jdbc-12.2.0.jre8.jar

    # Run tests with the Spark JARs included in the spark.jars configuration
    - name: Automation execution with Spark JARs
      run: |
        python runner.py
      env:
        SPARK_HOME: /opt/spark-3.3.0-bin-hadoop3.2
        PATH: $SPARK_HOME/bin:$PATH
        PYSPARK_SUBMIT_ARGS: --jars \
          $HOME/spark-jars/snowflake-jdbc-3.22.0.jar,\
          $HOME/spark-jars/postgresql-42.2.5.jar,\
          $HOME/spark-jars/azure-storage-8.6.6.jar,\
          $HOME/spark-jars/hadoop-azure-3.3.1.jar,\
          $HOME/spark-jars/mssql-jdbc-12.2.0.jre8.jar pyspark-shell
