name: Run PySpark ETL Transformation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  run-transformation:
    runs-on: ubuntu-latest

    env:
      ENV: qa
      PROJECT_ROOT: ${{ github.workspace }}
      POSTGRES_JAR: ${{ github.workspace }}/jars/postgresql-42.2.5.jar
      CUSTOMERS_CSV: ${{ github.workspace }}/input_files/customers.csv

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java (Required for Spark)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Apache Spark
        run: |
          curl -O https://downloads.apache.org/spark/spark-3.4.4/spark-3.4.4-bin-hadoop3.tgz
          tar xzf spark-3.4.4-bin-hadoop3.tgz
          echo "SPARK_HOME=$PWD/spark-3.4.4-bin-hadoop3" >> $GITHUB_ENV
          echo "$PWD/spark-3.4.4-bin-hadoop3/bin" >> $GITHUB_PATH

      - name: Verify Spark Installation
        run: |
          spark-submit --version

      - name: Run PySpark Transformation
        run: |
          spark-submit taf_dec/test_cases/transformation.py
