name: Run Transformation Script

on:
  push:
    branches:
      - main  # or whichever branch you want to run the script on

jobs:
  build:
    runs-on: ubuntu-latest  # or use your preferred OS, like windows-latest if required

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set the working directory to the folder containing your transformation.py
    - name: Run transformation script
      run: |
        cd taf_dec/tests/table4  # Adjust this to match where your transformation.py file is located in the repo
        python3 transformation.py
