name: ETL Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name:   Test with pytest
      run: |
        #  Change this to the correct relative path.
        if [ -d taf_dec ]; then
          echo "Directory taf_dec exists!"
          python runner2.py 
        elif [ -d  "taf_dec" ]; then
          echo "Directory taf_dec exists!"
          python runner2.py
        else
          echo "Directory taf_dec does NOT exist!"
          exit 1
        fi
      shell: /usr/bin/bash -e
