name: ETL Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Show Current Directory
      run: pwd
    - name: List Files and Directories
      run: ls -alR #Added recursive listing
    - name: Check for transformation.py
      run: |
        # Check for the existence of the directory and the file, adjust the path
        if [ -d "taf_dec/tests/table4" ] && [ -f "taf_dec/tests/table4/transformation.py" ]; then
          echo "taf_dec/tests/table4 and transformation.py exist!"
        else
          echo "taf_dec/tests/table4 or transformation.py does NOT exist!"
          exit 1
        fi
    - name: Test with pytest
      run: python runner2.py
      shell: /usr/bin/bash -e
